/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as CorporateRouteImport } from "./routes/corporate";
import { Route as FinanceRouteImport } from "./routes/finance";
import { Route as FleetRouteImport } from "./routes/fleet";
import { Route as InfoRouteImport } from "./routes/info";
import { Route as JoinRouteImport } from "./routes/join";
import { Route as LeaderboardRouteImport } from "./routes/leaderboard";
import { Route as NetworkRouteImport } from "./routes/network";
import { Route as RivalsRouteImport } from "./routes/rivals";
import { Route as RoutesRouteImport } from "./routes/routes";
import { Route as AircraftIdRouteImport } from "./routes/aircraft.$id";
import { Route as AirlineNpubRouteImport } from "./routes/airline.$npub";
import { Route as AirportIataRouteImport } from "./routes/airport.$iata";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const CorporateRoute = CorporateRouteImport.update({
  id: "/corporate",
  path: "/corporate",
  getParentRoute: () => rootRouteImport,
} as any);
const FinanceRoute = FinanceRouteImport.update({
  id: "/finance",
  path: "/finance",
  getParentRoute: () => rootRouteImport,
} as any);
const FleetRoute = FleetRouteImport.update({
  id: "/fleet",
  path: "/fleet",
  getParentRoute: () => rootRouteImport,
} as any);
const InfoRoute = InfoRouteImport.update({
  id: "/info",
  path: "/info",
  getParentRoute: () => rootRouteImport,
} as any);
const JoinRoute = JoinRouteImport.update({
  id: "/join",
  path: "/join",
  getParentRoute: () => rootRouteImport,
} as any);
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: "/leaderboard",
  path: "/leaderboard",
  getParentRoute: () => rootRouteImport,
} as any);
const NetworkRoute = NetworkRouteImport.update({
  id: "/network",
  path: "/network",
  getParentRoute: () => rootRouteImport,
} as any);
const RivalsRoute = RivalsRouteImport.update({
  id: "/rivals",
  path: "/rivals",
  getParentRoute: () => rootRouteImport,
} as any);
const RoutesRoute = RoutesRouteImport.update({
  id: "/routes",
  path: "/routes",
  getParentRoute: () => rootRouteImport,
} as any);
const AircraftIdRoute = AircraftIdRouteImport.update({
  id: "/aircraft/$id",
  path: "/aircraft/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const AirlineNpubRoute = AirlineNpubRouteImport.update({
  id: "/airline/$npub",
  path: "/airline/$npub",
  getParentRoute: () => rootRouteImport,
} as any);
const AirportIataRoute = AirportIataRouteImport.update({
  id: "/airport/$iata",
  path: "/airport/$iata",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/corporate": typeof CorporateRoute;
  "/finance": typeof FinanceRoute;
  "/fleet": typeof FleetRoute;
  "/info": typeof InfoRoute;
  "/join": typeof JoinRoute;
  "/leaderboard": typeof LeaderboardRoute;
  "/network": typeof NetworkRoute;
  "/rivals": typeof RivalsRoute;
  "/routes": typeof RoutesRoute;
  "/aircraft/$id": typeof AircraftIdRoute;
  "/airline/$npub": typeof AirlineNpubRoute;
  "/airport/$iata": typeof AirportIataRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/corporate": typeof CorporateRoute;
  "/finance": typeof FinanceRoute;
  "/fleet": typeof FleetRoute;
  "/info": typeof InfoRoute;
  "/join": typeof JoinRoute;
  "/leaderboard": typeof LeaderboardRoute;
  "/network": typeof NetworkRoute;
  "/rivals": typeof RivalsRoute;
  "/routes": typeof RoutesRoute;
  "/aircraft/$id": typeof AircraftIdRoute;
  "/airline/$npub": typeof AirlineNpubRoute;
  "/airport/$iata": typeof AirportIataRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/corporate": typeof CorporateRoute;
  "/finance": typeof FinanceRoute;
  "/fleet": typeof FleetRoute;
  "/info": typeof InfoRoute;
  "/join": typeof JoinRoute;
  "/leaderboard": typeof LeaderboardRoute;
  "/network": typeof NetworkRoute;
  "/rivals": typeof RivalsRoute;
  "/routes": typeof RoutesRoute;
  "/aircraft/$id": typeof AircraftIdRoute;
  "/airline/$npub": typeof AirlineNpubRoute;
  "/airport/$iata": typeof AirportIataRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/corporate"
    | "/finance"
    | "/fleet"
    | "/info"
    | "/join"
    | "/leaderboard"
    | "/network"
    | "/rivals"
    | "/routes"
    | "/aircraft/$id"
    | "/airline/$npub"
    | "/airport/$iata";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/corporate"
    | "/finance"
    | "/fleet"
    | "/info"
    | "/join"
    | "/leaderboard"
    | "/network"
    | "/rivals"
    | "/routes"
    | "/aircraft/$id"
    | "/airline/$npub"
    | "/airport/$iata";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/corporate"
    | "/finance"
    | "/fleet"
    | "/info"
    | "/join"
    | "/leaderboard"
    | "/network"
    | "/rivals"
    | "/routes"
    | "/aircraft/$id"
    | "/airline/$npub"
    | "/airport/$iata";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  CorporateRoute: typeof CorporateRoute;
  FinanceRoute: typeof FinanceRoute;
  FleetRoute: typeof FleetRoute;
  InfoRoute: typeof InfoRoute;
  JoinRoute: typeof JoinRoute;
  LeaderboardRoute: typeof LeaderboardRoute;
  NetworkRoute: typeof NetworkRoute;
  RivalsRoute: typeof RivalsRoute;
  RoutesRoute: typeof RoutesRoute;
  AircraftIdRoute: typeof AircraftIdRoute;
  AirlineNpubRoute: typeof AirlineNpubRoute;
  AirportIataRoute: typeof AirportIataRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/corporate": {
      id: "/corporate";
      path: "/corporate";
      fullPath: "/corporate";
      preLoaderRoute: typeof CorporateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/finance": {
      id: "/finance";
      path: "/finance";
      fullPath: "/finance";
      preLoaderRoute: typeof FinanceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/fleet": {
      id: "/fleet";
      path: "/fleet";
      fullPath: "/fleet";
      preLoaderRoute: typeof FleetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/info": {
      id: "/info";
      path: "/info";
      fullPath: "/info";
      preLoaderRoute: typeof InfoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/join": {
      id: "/join";
      path: "/join";
      fullPath: "/join";
      preLoaderRoute: typeof JoinRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/leaderboard": {
      id: "/leaderboard";
      path: "/leaderboard";
      fullPath: "/leaderboard";
      preLoaderRoute: typeof LeaderboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/network": {
      id: "/network";
      path: "/network";
      fullPath: "/network";
      preLoaderRoute: typeof NetworkRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/rivals": {
      id: "/rivals";
      path: "/rivals";
      fullPath: "/rivals";
      preLoaderRoute: typeof RivalsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/routes": {
      id: "/routes";
      path: "/routes";
      fullPath: "/routes";
      preLoaderRoute: typeof RoutesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/aircraft/$id": {
      id: "/aircraft/$id";
      path: "/aircraft/$id";
      fullPath: "/aircraft/$id";
      preLoaderRoute: typeof AircraftIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/airline/$npub": {
      id: "/airline/$npub";
      path: "/airline/$npub";
      fullPath: "/airline/$npub";
      preLoaderRoute: typeof AirlineNpubRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/airport/$iata": {
      id: "/airport/$iata";
      path: "/airport/$iata";
      fullPath: "/airport/$iata";
      preLoaderRoute: typeof AirportIataRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CorporateRoute: CorporateRoute,
  FinanceRoute: FinanceRoute,
  FleetRoute: FleetRoute,
  InfoRoute: InfoRoute,
  JoinRoute: JoinRoute,
  LeaderboardRoute: LeaderboardRoute,
  NetworkRoute: NetworkRoute,
  RivalsRoute: RivalsRoute,
  RoutesRoute: RoutesRoute,
  AircraftIdRoute: AircraftIdRoute,
  AirlineNpubRoute: AirlineNpubRoute,
  AirportIataRoute: AirportIataRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
