#!/usr/bin/env node
/**
 * generate-fuel-epochs.ts — precomputes the fuel price at the start of every
 * engine day (epoch) into packages/core/src/fuelEpochs.ts.
 *
 * The fuel price is a deterministic random walk from genesis, one step per
 * tick. Without this table the first price of a session walks every tick
 * since genesis (17M+ steps by late 2026, seconds on a phone, and once more
 * in each worker). The table is produced by the same `stepFuelPrice` the game
 * uses, so prices stay bit-identical; `fuel.test.ts` re-walks a sample of
 * days against it.
 *
 * Usage (after `pnpm --filter @acars/core build`):
 *   node --experimental-strip-types scripts/generate-fuel-epochs.ts [--until 2028-12-31] [--check]
 *
 * --check regenerates in memory and fails if the committed table differs.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  FUEL_PRICE_EPOCH_TICKS,
  FUEL_PRICE_MEAN_PER_KG,
  GENESIS_TIME,
  stepFuelPrice,
  TICK_DURATION,
} from "../packages/core/dist/index.js";

const OUT = resolve(import.meta.dirname, "../packages/core/src/fuelEpochs.ts");
const args = process.argv.slice(2);
const untilArg = args.includes("--until") ? args[args.indexOf("--until") + 1] : "2028-12-31";
const check = args.includes("--check");

const untilTick = Math.floor((Date.parse(`${untilArg}T00:00:00Z`) - GENESIS_TIME) / TICK_DURATION);
const lastEpoch = Math.ceil(untilTick / FUEL_PRICE_EPOCH_TICKS);

const prices: number[] = [FUEL_PRICE_MEAN_PER_KG];
let price = FUEL_PRICE_MEAN_PER_KG;
for (let epoch = 1; epoch <= lastEpoch; epoch++) {
  for (
    let tick = (epoch - 1) * FUEL_PRICE_EPOCH_TICKS;
    tick < epoch * FUEL_PRICE_EPOCH_TICKS;
    tick++
  ) {
    price = stepFuelPrice(price, tick);
  }
  prices.push(price);
}

const rows: string[] = [];
for (let i = 0; i < prices.length; i += 12) rows.push(`  ${prices.slice(i, i + 12).join(", ")},`);
const source = `// Generated by scripts/generate-fuel-epochs.ts — do not edit by hand.
// Fuel price (fixed-point, per kg) at the start of each engine day, from
// genesis through ${untilArg}: entry n is the price at tick n × FUEL_PRICE_EPOCH_TICKS.
export const FUEL_EPOCH_START_PRICES: readonly number[] = [
${rows.join("\n")}
];
`;

if (check) {
  // Compare the numbers, not the text: the formatter may re-wrap the file.
  const committedBody = readFileSync(OUT, "utf8").split("= [")[1] ?? "";
  const committed = committedBody.match(/\d+/g)?.map(Number) ?? [];
  if (committed.length !== prices.length || committed.some((value, i) => value !== prices[i])) {
    console.error("fuelEpochs.ts is out of date: run scripts/generate-fuel-epochs.ts");
    process.exit(1);
  }
  console.log(`fuelEpochs.ts matches (${prices.length} days).`);
} else {
  writeFileSync(OUT, source);
  console.log(`Wrote ${prices.length} day-start prices through ${untilArg} to ${OUT}`);
}
